title: "Análise de dados espaço-temporais"
author: "Alexandro Gularte Schafer"
logo: "logo.png"         # se estiver em book/images/, use "images/logo.png"
only_build_toc_files: true

execute:
  execute_notebooks: "auto"   # roda no CI
  timeout: 180
  cache: "_cache"             # acelera builds

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution

html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true

repository:
  url: https://github.com/Alexandrogschafer/spatio-temporal-data-analysis
  branch: main
  path_to_book: "."

sphinx:
  config:
    html_show_copyright: false
    numsec_number_heading: true

exclude_patterns:
  - "**/.ipynb_checkpoints"
  - "_build"
  - "_cache"
