title: Análise de dados espaço-temporais
author: Alexandro Gularte Schafer
logo: logo.png  # Opcional
execute:
  execute_notebooks: "off"  # Desativa a execução de notebooks (não é necessário no seu caso)
html:
  use_repository_button: true  # Adiciona um botão para o repositório
  use_edit_page_button: true   # Adiciona um botão para editar a página
  use_issues_button: true      # Adiciona um botão para reportar problemas
repository:
  url: https://github.com/Alexandrogschafer/spatio-temporal-data-analysis
  branch: main