title: Análise de dados espaço-temporais
author: Alexandro Gularte Schafer
description: "Um livro sobre análise de dados espaço-temporais, com exemplos práticos e teóricos."
logo: logo.png  # Certifique-se de que o arquivo está na raiz ou ajuste o caminho

execute:
  execute_notebooks: "off"

html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  use_fullscreen_button: true
  use_download_button: true

repository:
  url: https://github.com/Alexandrogschafer/spatio-temporal-data-analysis
  branch: main

