title: Análise de dados espaço-temporais
author: Alexandro Gularte Schafer
logo: logo.png  # Opcional
execute:
  execute_notebooks: "off"
html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
repository:
  url: https://github.com/Alexandrogschafer/spatio-temporal-data-analysis
  branch: gh-pages